# Generated by Django 3.2.3 on 2021-07-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app_dynamic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='City_Name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='price',
            new_name='Famous_Food',
        ),
        migrations.AddField(
            model_name='image',
            name='Famous_River',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='State_Name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
