# Generated by Django 3.2.3 on 2021-07-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app_dynamic', '0002_auto_20210712_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Population',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='Position',
            field=models.ImageField(default=0, max_length=50, upload_to=''),
            preserve_default=False,
        ),
    ]
