# Generated by Django 3.2.3 on 2021-07-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app_dynamic', '0003_auto_20210712_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Position',
            field=models.CharField(max_length=50),
        ),
    ]
