# Generated by Django 3.2.3 on 2021-07-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app_dynamic', '0004_alter_image_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Position',
            new_name='Caption',
        ),
    ]
